spring.datasource.url=jdbc:postgresql://ep-crimson-pond-acsobv42-pooler.sa-east-1.aws.neon.tech/prode?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_GNcV4labEI8Y

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration